# permissions for end users to edit capturers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: capturer-editor-role
rules:
- apiGroups:
  - capturer.stable.example.com
  resources:
  - capturers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - capturer.stable.example.com
  resources:
  - capturers/status
  verbs:
  - get
