# permissions for end users to view capturers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: capturer-viewer-role
rules:
- apiGroups:
  - capturer.stable.example.com
  resources:
  - capturers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - capturer.stable.example.com
  resources:
  - capturers/status
  verbs:
  - get
