# permissions for end users to edit outputs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: output-editor-role
rules:
- apiGroups:
  - capturer.stable.example.com
  resources:
  - outputs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - capturer.stable.example.com
  resources:
  - outputs/status
  verbs:
  - get
