
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- resources:
  - configmaps/status
  verbs:
  - get
- resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- resources:
  - secrets/status
  verbs:
  - get
- resources:
  - serviceaccounts
  verbs:
  - get
  - list
  - watch
- resources:
  - serviceaccounts/status
  verbs:
  - get
- resources:
  - services
  verbs:
  - get
  - list
  - watch
- resources:
  - services/status
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments/status
  verbs:
  - get
- apiGroups:
  - capturer
  resources:
  - outputs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - capturer
  resources:
  - outputs/status
  verbs:
  - get
- apiGroups:
  - capturer.stable.example.com
  resources:
  - capturers
  verbs:
  - get
  - list
- apiGroups:
  - capturer.stable.example.com
  resources:
  - capturers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - capturer.stable.example.com
  resources:
  - outputs
  verbs:
  - get
  - list
- apiGroups:
  - capturer.stable.example.com
  resources:
  - outputs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rbac
  resources:
  - clusterrolebindings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rbac
  resources:
  - clusterrolebindings/status
  verbs:
  - get
- apiGroups:
  - rbac
  resources:
  - clusterroles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rbac
  resources:
  - clusterroles/status
  verbs:
  - get
