apiVersion: capturer.stable.example.com/v1alpha1
kind: Output
metadata:
  name: clusterrole-github-output
spec:
  github:
    config:
      repositoryUrl: https://github.com/$YOURNAME/$REPONAME.git
      baseBranch: master
      manifestPath: clusterrole.yaml
      author:
        name: $YOURNAME
        email: $YOUREMAIL
    localFilePath: /tmp/coredns/
