apiVersion: capturer.stable.example.com/v1alpha1
kind: Output
metadata:
  name: serviceaccount-github-output
spec:
  github:
    config:
      repositoryUrl: https://github.com/yourname/reponame.git
      baseBranch: master
      manifestPath: serviceaccount.yaml
      author:
        name: hoge
        email: hoge@example.com
    localFilePath: /tmp/coredns/
