apiVersion: capturer.stable.example.com/v1alpha1
kind: Capturer
metadata:
  name: clusterrolebinding-capturer
spec:
  namespacedResource: false
  resourceKind: ClusterRoleBinding
  resourceName: system:coredns
  outputs:
    - clusterrolebinding-github-output
    - clusterrolebinding-slack-output
