apiVersion: capturer.stable.example.com/v1alpha1
kind: Capturer
metadata:
  name: deployment-capturer
spec:
  resourceKind: Deployment
  resourceNamespace: kube-system
  resourceName: coredns
  output: deployment-output
