apiVersion: capturer.stable.example.com/v1alpha1
kind: Capturer
metadata:
  name: secret-capturer
spec:
  namespacedResource: true
  resourceKind: Secret
  resourceNamespace: kube-system
  resourceName: coredns-token-xxxx
  outputs:
    - secret-github-output
    - secret-slack-output
