apiVersion: capturer.stable.example.com/v1alpha1
kind: Capturer
metadata:
  name: service-capturer
spec:
  namespacedResource: true
  resourceKind: Service
  resourceNamespace: kube-system
  resourceName: kube-dns
  outputs:
    - service-github-output
    - service-slack-output
