apiVersion: capturer.stable.example.com/v1alpha1
kind: Capturer
metadata:
  name: serviceaccount-capturer
spec:
  namespacedResource: true
  resourceKind: ServiceAccount
  resourceNamespace: kube-system
  resourceName: coredns
  outputs:
    - serviceaccount-github-output
    - serviceaccount-slack-output
