name: test
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        go: [1.14, 1.15]
        os: [ubuntu-18.04, ubuntu-20.04]

    name: all
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - uses: actions/cache@v2
        id: cache-go-sum
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: download dependencies
        if: steps.cache-go-sum.outputs.cache-hit != 'true'
        run: go mod download

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29

      - uses: RyanSiu1995/kubebuilder-action@v1.2

      - name: test
        run: make test
